In [2]:
print('Hello Jupyter!')

Hello Jupyter!


In [3]:
import pandas as pd
import numpy as np

data_1 = {'AAA': [6, 3, 7, 5], 
          'BBB': [24, 54, 12, 97],
          'CCC': [745, 274, 874, 300], 
          'DDD': [0, 123, 456, 789]}

data_2 = np.random.randint(0,20,(5,5))

df = pd.DataFrame(data_1)

data_2

array([[ 8,  6, 15,  3, 14],
       [ 3,  8, 16, 10, 15],
       [18,  5, 10,  0,  7],
       [12, 14,  9,  6,  4],
       [18, 14, 17,  9,  3]])

In [4]:
sorted_data_2 = np.sort(data_2, axis = 0)
sorted_data_2

array([[ 3,  5,  9,  0,  3],
       [ 8,  6, 10,  3,  4],
       [12,  8, 15,  6,  7],
       [18, 14, 16,  9, 14],
       [18, 14, 17, 10, 15]])

In [5]:
np.sum(data_2 >= 15)

6

In [6]:
np.any(data_2 == 0)

True

In [7]:
data_3 = np.random.randint(0,10,(3,3))
data_3

array([[9, 7, 5],
       [9, 2, 3],
       [4, 1, 8]])

In [8]:
np.add.reduce(data_3, axis=1)

array([21, 14, 13])

In [9]:
np.add.accumulate(data_3, axis=1)

array([[ 9, 16, 21],
       [ 9, 11, 14],
       [ 4,  5, 13]])

In [10]:
np.sum(data_3, axis=1)

array([21, 14, 13])

In [11]:
np.add.outer(data_3,1)

array([[10,  8,  6],
       [10,  3,  4],
       [ 5,  2,  9]])

In [12]:
data_3

array([[9, 7, 5],
       [9, 2, 3],
       [4, 1, 8]])

In [13]:
np.std(data_3)

2.8674417556808756

In [14]:
np.var(data_3)

8.222222222222221

In [15]:
print(np.std(data_3)**2)

8.222222222222221


In [16]:
np.median(data_3)

5.0

In [17]:
np.split(data_3,[2])

[array([[9, 7, 5],
        [9, 2, 3]]),
 array([[4, 1, 8]])]

привет мир. меня зовут Юлиан. я изучаю юпитер ноутбук. 

https://mypresentation.ru/documents_6/421fdbfc4432982aa70359d2b97ff560/img6.jpg

In [18]:
ser = pd.Series([1,5,2,4,6,1])
ser

0    1
1    5
2    2
3    4
4    6
5    1
dtype: int64

In [19]:
pd.DataFrame(data_2, 
             index=['row1','row2','row3','row4','row5'],
             columns=['col1', 'col2', 'col3', 'col4', 'col5'])

col1  col2  col3  col4  col5
row1     8     6    15     3    14
row2     3     8    16    10    15
row3    18     5    10     0     7
row4    12    14     9     6     4
row5    18    14    17     9     3

Быстрое создание датафрейма:

In [20]:
def make_df(cols, ind):
    data = {c:[str(c)+str(i) for i in ind] 
            for c in cols}
    return pd.DataFrame(data, ind)

make_df('ABCDE', range(5))

A   B   C   D   E
0  A0  B0  C0  D0  E0
1  A1  B1  C1  D1  E1
2  A2  B2  C2  D2  E2
3  A3  B3  C3  D3  E3
4  A4  B4  C4  D4  E4

In [21]:
pd.concat?